services:
  backend:
    image: gautamcov01/backend:latest
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: gautamcov01/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy