name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v4.3.0

      - name: Login to Docker hub
        uses: docker/login-action@v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image with cache
        uses: docker/build-push-action@v7.3.0
        with:
          context: ./backend
          tags: backend:latest
          load: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend:cache-build
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/backend:cache-build,mode=max,image-manifest=true,oci-mediatypes=true

      - name: Build frontend image with cache
        uses: docker/build-push-action@v7.3.0
        with:
          context: ./frontend
          tags: frontend:latest
          load: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/frontend:cache-build
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/frontend:cache-build,mode=max,image-manifest=true,oci-mediatypes=true

      - name: Start application
        run: docker compose up --wait

      - name: Check containers
        run: docker compose ps

      - name: Test frontend
        run: curl -f --retry 5 --retry-delay 2 http://localhost:3000

      - name: Test backend through Nginx
        run: curl -f --retry 5 --retry-delay 2 http://localhost:3000/api/status

      - name: Show logs
        if: failure()
        run: docker compose logs

      - name: Stop application
        if: always()
        run: docker compose down
